version: "3"
services:
  mongodb:
    image: mongo:6.0.4
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
